In [1]:
import pandas as pd
import numpy as np

In [2]:
QnA1 = pd.read_csv('./data/B 의류(15,826)_new.csv')
QnA1

,SPEAKER,SENTENCE,DOMAINID,DOMAIN,CATEGORY,SPEAKERID,SENTENCEID,MAIN,SUB,QA,QACNCT,MQ,SQ,UA,SA,개체명,용어사전,지식베이스,Unnamed: 18
0,고객,신발은 여기 있는 게 다예요?,B,의복의류점,신발,1,1,종류별신발제품문의요청,NaN,Q,NaN,신발은 여기 있는 게 다예요?,NaN,NaN,NaN,"신발, 여기",NaN,신발/제품,0.0
1,점원,네 성인이나 아동 다 있어요,B,의복의류점,신발,0,2,종류별신발제품문의요청,NaN,A,NaN,NaN,NaN,NaN,네 성인이나 아동 다 있어요,"성인, 아동",NaN,"성인/대상, 아동/대상",NaN
2,점원,발 사이즈 몇 신으세요?,B,의복의류점,신발,0,3,종류별신발제품문의요청,사이즈,Q,NaN,NaN,발 사이즈 몇 신으세요?,NaN,NaN,"발, 사이즈",NaN,NaN,NaN
3,고객,230이요,B,의복의류점,신발,1,4,종류별신발제품문의요청,사이즈,A,NaN,NaN,NaN,230이요,NaN,230,NaN,230/사이즈,NaN
4,점원,편하게 신을 수 있는 거 찾으세요?,B,의복의류점,신발,0,5,착화감,제품문의,Q,NaN,NaN,편하게 신을 수 있는 거 찾으세요?,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15821,고객,이 쿠폰에 적립해주세요,B,의복의류점,액세서리,1,922,쿠폰시적립요청,NaN,Q,NaN,이 쿠폰에 적립해주세요,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15822,고객,사은품 받으려면 쿠폰 몇 개 모아야 해요?,B,의복의류점,액세서리,1,923,쿠폰적용사음품문의,NaN,Q,NaN,사은품 받으려면 쿠폰 몇 개 모아야 해요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15823,고객,쿠폰 몇 개 모으면 사은품 받을 수 있어요?,B,의복의류점,액세서리,1,924,쿠폰적용사음품문의,NaN,Q,NaN,쿠폰 몇 개 모으면 사은품 받을 수 있어요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15824,고객,쿠폰 몇 장 모아야 사은품 받을 수 있나요?,B,의복의류점,액세서리,1,925,쿠폰적용사음품문의,NaN,Q,NaN,쿠폰 몇 장 모아야 사은품 받을 수 있나요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15825,고객,사은품 받으려면 쿠폰 몇 장 있어야 돼요?,B,의복의류점,액세서리,1,926,쿠폰적용사음품문의,NaN,Q,NaN,사은품 받으려면 쿠폰 몇 장 있어야 돼요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
QnA1.columns

Index(['SPEAKER', 'SENTENCE', 'DOMAINID', 'DOMAIN', 'CATEGORY', 'SPEAKERID',
       'SENTENCEID', 'MAIN', 'SUB', 'QA', 'QACNCT', 'MQ', 'SQ', 'UA', 'SA',
       '개체명', '용어사전', '지식베이스', 'Unnamed: 18'],
      dtype='object')

In [4]:
QnA1['MAIN'].values

array(['종류별신발제품문의요청', '종류별신발제품문의요청', '종류별신발제품문의요청', ..., '쿠폰적용사음품문의',
       '쿠폰적용사음품문의', '쿠폰적용사음품문의'], dtype=object)

In [5]:
QnA1[['SPEAKER','SENTENCE','MAIN']][:4]

  SPEAKER          SENTENCE         MAIN
0      고객  신발은 여기 있는 게 다예요?  종류별신발제품문의요청
1      점원   네 성인이나 아동 다 있어요  종류별신발제품문의요청
2      점원     발 사이즈 몇 신으세요?  종류별신발제품문의요청
3      고객             230이요  종류별신발제품문의요청

In [6]:
recommend = QnA1[QnA1['SENTENCE'].str.contains('추천해')]
recommend['SENTENCE'].count()

47

In [7]:
QnA2 = pd.read_csv('./data/의류_train.csv')
QnA2

,IDX,발화자,발화문,카테고리,QA번호,QA여부,감성,인텐트,가격,수량,크기,장소,조직,사람,시간,날짜,상품명,상담번호,상담내순번
0,1,c,아침도 아니고 밤 12시 30분에 결제한 건데도 그런가요?,의류,67435,q,m,주문_취소_확인,NaN,NaN,NaN,NaN,NaN,NaN,밤 12시 30분,NaN,NaN,67435,1
1,2,s,네 저희가 보통 그날 12시에 발주 마감이여서요 일단 내일 물건 오는 대로 보내드릴게요.,의류,67435,a,m,주문_취소_확인,NaN,NaN,NaN,NaN,NaN,NaN,12시,NaN,NaN,67435,2
2,3,c,실수로 취소하면 재주문해야 하는 거죠?,의류,34557,q,m,주문_취소_확인,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34557,1
3,4,s,네 취소하였을 경우 재주문해 주셔야 하는 점 양해 부탁드립니다.,의류,34557,a,m,주문_취소_확인,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34557,2
4,5,c,택배비 따로 추가되나요?,의류,17,q,m,배송_비용_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2186,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419423,419424,s,받아보신 상품이 프리 사이즈가 맞습니다 동봉된 택은 제작공장에서 표기된 걸로 저희 ...,의류,64694,a,m,주문_오류_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64694,2
419424,419425,c,어제는 해주겠지 했는데 또 안 했네요?,의류,46330,q,m,주문_오류_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46330,1
419425,419426,s,두 가지 상품 전부입고 지연 상품이라 발송해 드리지 못하고 있는 것 같아요 한 가지...,의류,46330,a,m,주문_오류_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46330,2
419426,419427,c,172/75xL 32사이즈로 주문했는데 왜 이래 낍니까?,의류,68688,q,m,주문_오류_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68688,1
419427,419428,s,만족시켜 드리지 못해 죄송합니다.,의류,68688,a,m,주문_오류_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68688,2

In [8]:
QnA2['인텐트'].values

array(['주문_취소_확인', '주문_취소_확인', '주문_취소_확인', ..., '주문_오류_질문', '주문_오류_질문',
       '주문_오류_질문'], dtype=object)

In [9]:
QnA2[['발화자','발화문','인텐트']][:4]

  발화자                                                발화문       인텐트
0   c                   아침도 아니고 밤 12시 30분에 결제한 건데도 그런가요?  주문_취소_확인
1   s  네 저희가 보통 그날 12시에 발주 마감이여서요 일단 내일 물건 오는 대로 보내드릴게요.  주문_취소_확인
2   c                              실수로 취소하면 재주문해야 하는 거죠?  주문_취소_확인
3   s                네 취소하였을 경우 재주문해 주셔야 하는 점 양해 부탁드립니다.  주문_취소_확인

In [10]:
QnA2[QnA2['발화문'].str.contains('추천해')]

,IDX,발화자,발화문,카테고리,QA번호,QA여부,감성,인텐트,가격,수량,크기,장소,조직,사람,시간,날짜,상품명,상담번호,상담내순번
3199,3200,s,정사이즈 기준으로 제작된 상품으로 평소 착용하시는 사이즈로 구매하시는 것을 추천해 ...,의류,194510,a,m,배송_일반_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194510,2
3839,3840,s,검수 후 출고도와 드릴게요. 손세탁 추천해 드립니다.,의류,190034,a,m,배송_일반_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190034,2
4605,4606,s,다른 상품으로 추천해 드릴테니 교환 부탁드립니다.,의류,148462,a,m,제품_품질_요청,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148462,2
7944,7945,s,의류 브랜드 피턴 진입니다. 해당 상품은 휘트니스웨어로 추천해 드리며 래쉬가드 소재...,의류,163367,a,m,제품_구성_질문,NaN,NaN,NaN,NaN,피턴 진,NaN,NaN,NaN,NaN,163367,2
9555,9556,c,원래 안주시는 줄 알고 있었는데 사이트를 이 추천해서 같이 구매했던 지인은 일반 깔...,의류,207034,q,m,제품_구성_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,일반 깔창,207034,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404420,404421,s,지금 손님이 보신 주름진 치마부터 아까 제가 추천해드릴 검은색 치마 종류까지가 만원입니다,의류,11,a,m,제품_가격_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,치마,13002,22
405161,405162,c,추천해주신 바지 두 벌 구매할 건데 할인 가능하죠?,의류,136286,q,m,제품_가격_질문,NaN,두 벌,NaN,NaN,NaN,NaN,NaN,NaN,바지,136286,1
407801,407802,c,추천해주신 바지랑 같이 코디된 티셔츠도 같이 사고 싶은데 할인되나요?,의류,136268,q,m,제품_가격_질문,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,바지|티셔츠,136268,1
417788,417789,s,보통 입으시는 사이즈가 110이면 2x L 사이즈를 추천해드려요 상품에 따라 출고일...,의류,61329,a,m,배송_날짜_요청,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61329,2
418739,418740,c,사장님이 적극 추천해 주시니까 저도 입어볼께요,의류,48,q,m,결제_일반_요청,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,98

In [11]:
QnA2[QnA2['인텐트'].str.contains('추천')]

,IDX,발화자,발화문,카테고리,QA번호,QA여부,감성,인텐트,가격,수량,크기,장소,조직,사람,시간,날짜,상품명,상담번호,상담내순번
16161,16162,s,그럼 구십호 보세요,의류,40,q,m,제품_추천_확인,NaN,NaN,구십호,NaN,NaN,NaN,NaN,NaN,NaN,13179,79
16162,16163,c,구십호요?,의류,154,q,m,제품_추천_확인,NaN,NaN,구십호,NaN,NaN,NaN,NaN,NaN,NaN,13179,304
16163,16164,s,네,의류,154,a,m,제품_추천_확인,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13179,305
16164,16165,c,"아, 애들이 이런 걸 입어요?",의류,3,q,m,제품_추천_확인,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1019,6
16165,16166,s,그럼요. 애들이 너무 좋아요,의류,3,a,m,제품_추천_확인,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1019,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360985,360986,s,핏감 있게 나온 제품이라베이지라 하더라도 살쪄 보이진 않으시구요 팔뚝살 또는 어깨살...,의류,201976,a,m,제품_추천_비교,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,베이지|네이비,201976,2
360986,360987,c,66사이즈 구매하고 싶은데 73으로 선택해야 되지요?,의류,195261,q,m,제품_추천_비교,NaN,NaN,66사이즈|73,NaN,NaN,NaN,NaN,NaN,NaN,195261,1
360987,360988,s,66사이즈 70 사이즈로 참고하셔서 구매 부탁드려요.,의류,195261,a,m,제품_추천_비교,NaN,NaN,66사이즈|70 사이즈,NaN,NaN,NaN,NaN,NaN,NaN,195261,2
360988,360989,c,"평소 95사이즈 입고 겨울 패딩, 가디건은 100사이즈 입는데 이 상품 사이즈 어떻...",의류,184390,q,m,제품_추천_비교,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,겨울 패딩|가디건,184390,1
360989,360990,s,본 제품은 신축성이 좋아 평소 착용하시는 95사이즈로 구매해 주셔도 좋습니다.,의류,184390,a,m,제품_추천_비교,NaN,NaN,95,NaN,NaN,NaN,NaN,NaN,NaN,184390,2